### ISSUE TITLE
Jan 2 new error

### ISSUE THREAD

**Issue by kalcan83** [ninneman/mbgui#10]
kalcan83@kalcan83-posiedon:~/Downloads$ ./mbguiJan2.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.1/tkinter/__init__.py", line 1402, in __call__
    return self.func(*args)
  File "./mbguiJan2.py", line 65, in convert
    final_output = outfile_full_base + "." + self.txttype[0].get()
TypeError: 'StringVar' object does not support indexing

**Comment by ninneman** [comment]
Fixed. Bad on me for not testing.
